# Generated by Django 5.1.1 on 2024-10-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rceipe',
            new_name='Recipe',
        ),
    ]
